import AppKit

/// Mirrors what you copy onto the robot, if you switch it on.
///
/// It is off until you turn it on, and even then it refuses anything a
/// password manager has marked. 1Password, Bitwarden and the rest set these
/// types precisely so that tools like this one leave credentials alone.
@MainActor
final class Clipboard {
    private var lastChange = NSPasteboard.general.changeCount
    private var timer: Timer?

    /// Set by anything that marks its own copy as not for other eyes.
    private static let refuse: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    func start(_ onCopy: @escaping (String) -> Void) {
        stop()
        lastChange = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { _ in
            Task { @MainActor in
                let pb = NSPasteboard.general
                guard pb.changeCount != self.lastChange else { return }
                self.lastChange = pb.changeCount
                let types = Set((pb.types ?? []).map(\.rawValue))
                guard types.isDisjoint(with: Self.refuse) else { return }
                guard let s = pb.string(forType: .string) else { return }
                let t = s.trimmingCharacters(in: .whitespacesAndNewlines)
                guard !t.isEmpty else { return }
                onCopy(t.replacingOccurrences(of: "\n", with: " "))
            }
        }
    }

    func stop() { timer?.invalidate(); timer = nil }
}
