<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>rafiq</AssemblyName>
    <RootNamespace>Rafiq.Cli</RootNamespace>
    <Version>1.2.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rafiq.Core\Rafiq.Core.csproj" />
  </ItemGroup>
</Project>
